### PR TITLE
New metric schema

### PR DESCRIPTION
**Pull request by marcin-krolik**
- handling of new namespace added
- applied changes to unit tests

### CODE REVIEW

**Comment by tiffanyfj** [comment]
It looks good to me, but I am still a little uncertain on the dynamic label stuff...so might be good to get a second opinion too. Also if you can have it be one commit vs a commit and a merge commit.

**Comment by geauxvirtual** [comment]
Why is the `hostname` tag being removed with this PR?

**Comment by marcin-krolik** [comment]
@geauxvirtual ```hostname``` tag is added by the framework as a standard tag for each metric. Not need to handle it in collectors

**Comment by geauxvirtual** [comment]
The framework is tagging where the plugin is running. This collector plugin is a proxy plugin that can collect from different RabbitMQ clusters that may not be running where the plugin is running. The RabbitMQ cluster source is important part of describing where the metric is coming from.

**Comment by marcin-krolik** [comment]
@geauxvirtual: Thanks for explanation. I will add cluster source as a tag collected metrics. Any suggestions for tag key or ```cluster_source``` is OK?

**Comment by marcin-krolik** [comment]
Hostname tag restored (removed commit which introduced this change)

**Comment by candysmurf** [comment]
LGTM

**Pull request merged**
